CREATE TABLE BOOK (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    ISBN VARCHAR(10) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    PUBLISHER VARCHAR(100) NOT NULL,
    PRICE DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (ID)
);
